# Generated by Django 6.1 on 2026-08-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='hours_played',
            new_name='duration_hours',
        ),
        migrations.AddField(
            model_name='game',
            name='untracked_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
