# Generated by Django 6.1.1 on 2026-09-03 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_hours_played_gamesession_duration_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_on', models.DateField()),
                ('body', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='tracker.game')),
            ],
            options={
                'ordering': ['-written_on'],
            },
        ),
    ]
