# Generated by Django 6.1.1 on 2026-09-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_journalentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-played_on']},
        ),
    ]
